cursor:
  text: '#000000'
  cursor: '#cdd6f4'
vi_mode_cursor:
  text: '#000000'
  cursor: '#cdd6f4'
selection:
  text: CellBackground
  background: '#a89984'
primary:
  background: '#1e1e2e'
  foreground: '#cdd6f4'
normal:
  black:   '#1e1e2e'
  red:     '#f38ba8'
  green:   '#a6e3a1'
  yellow:  '#f9e2af'
  blue:    '#89b4fa'
  magenta: '#f5c2e7'
  cyan:    '#94e2d5'
  white:   '#bac2de'
bright:
  black:   '#585b70'
  red:     '#f38ba8'
  green:   '#a6e3a1'
  yellow:  '#f9e2af'
  blue:    '#89b4fa'
  magenta: '#f5c2e7'
  cyan:    '#94e2d5'
  white:   '#cdd6f4'
