cursor:
  text: '#000000'
  cursor: '#d3c6aa'
vi_mode_cursor:
  text: '#000000'
  cursor: '#d3c6aa'
selection:
  text: CellBackground
  background: '#a89984'
primary:
  background: '#2d353b'
  foreground: '#d3c6aa'
normal:
  black:   '#2d353b'
  red:     '#e67e80'
  green:   '#a7c080'
  yellow:  '#dbbc7f'
  blue:    '#7fbbb3'
  magenta: '#d699b6'
  cyan:    '#83c092'
  white:   '#d3c6aa'
bright:
  black:   '#5c6a72'
  red:     '#f85552'
  green:   '#8da101'
  yellow:  '#dfa000'
  blue:    '#3a94c5'
  magenta: '#df69ba'
  cyan:    '#35a77c'
  white:   '#dfddc8'
