cursor:
  text: '#000000'
  cursor: '#d98b71'
vi_mode_cursor:
  text: '#000000'
  cursor: '#d98b71'
selection:
  text: CellBackground
  background: '#a89984'
primary:
  background: '#fbf1c7'
  foreground: '#282828'
normal:
  black:   '#fbf1c7' # Bg0
  red:     '#cc241d'
  green:   '#98971a'
  yellow:  '#d79921'
  blue:    '#458588'
  magenta: '#b16286'
  cyan:    '#689d6a'
  white:   '#7c6f64' # Fg4
bright:
  black:   '#d5c4a1' # Bg2
  red:     '#9d0006'
  green:   '#79740e'
  yellow:  '#b57614'
  blue:    '#076678'
  magenta: '#8f3f71'
  cyan:    '#427b58'
  white:   '#282828' # Fg0
indexed_colors:
  - { index: 166, color: '#d65d0c' } # Orange
