cursor:
  text: '#000000'
  cursor: '#d98b71'
vi_mode_cursor:
  text: '#000000'
  cursor: '#d98b71'
selection:
  text: CellBackground
  background: '#a89984'
primary:
  background: '#fbf1c7'
  foreground: '#3c3836'
normal:
  black:   '#282828'
  red:     '#cc241d'
  green:   '#98971a'
  yellow:  '#d79921'
  blue:    '#458588'
  magenta: '#b16286'
  cyan:    '#689d6a'
  white:   '#a89984'
bright:
  black:   '#928374'
  red:     '#fb4934'
  green:   '#b8bb26'
  yellow:  '#fabd2f'
  blue:    '#83a598'
  magenta: '#d3869b'
  cyan:    '#8ec07c'
  white:   '#3c3836'
