cursor:
  text: '#000000'
  cursor: '#d98b71'
vi_mode_cursor:
  text: '#000000'
  cursor: '#d98b71'
selection:
  text: CellBackground
  background: '#a89984'
primary:
  background: '#282828'
  foreground: '#fbf1c7'
normal:
  black:   '#282828' # Bg0
  red:     '#cc241d'
  green:   '#98971a'
  yellow:  '#d79921'
  blue:    '#458588'
  magenta: '#b16286'
  cyan:    '#689d6a'
  white:   '#d5c4a1' # Fg2
bright:
  black:   '#504945' # Bg2
  red:     '#fb4934'
  green:   '#b8bb26'
  yellow:  '#fabd2f'
  blue:    '#83a598'
  magenta: '#d3869b'
  cyan:    '#8ec07c'
  white:   '#fbf1c7' # Fg0
indexed_colors:
  - { index: 166, color: '#d65d0c' } # Orange
